### PR TITLE
Simplistic approach to avoid unique parallel

### PR DESCRIPTION
**Pull request by guillep2k**
@zeripath

This is the idea I had for avoiding double processing of the same key in unique_queue_channel. It probably has many flaws, but I'd wanted to show it to you anyway.

### CODE REVIEW

**Comment by zeripath** [comment]
So actually the simplest solution is to wrap the queue - I'll open a private branch with a solution.

**Comment by zeripath** [comment]
So actually I think this would do it...

```go
func NoParallelQueueHandler(handle queue.HandlerFunc) queue.HandlerFunc {
	tlock := sync.Mutex{}
	table := map[Data]int{}
	return func(data ...Data) {
		for _, datum := range data {
			tlock.Lock()
			count := table[datum]
			if count > 0 {
				table[datum] = count + 1
				tlock.Unlock()
				continue
			}
			count++
			table[datum] = count + 1
			tlock.Unlock()
			for count > 0 {
				handle(datum)
				tlock.Lock()
				count = table[datum]
				count--
				if count == 0 {
					delete(table, datum)
					tlock.Unlock()
					break
				}
				table[datum] = count
				tlock.Unlock()
			}
		}
	}
}
```

**Comment by guillep2k** [comment]
But that's one worker, right? What if there are other workers?

(Also, I don't think `count` needs to grow > 2 for most cases; it could be a setting).

**Comment by zeripath** [comment]
You wrap the handler you pass to the queue... - then it's all workers.

**Comment by guillep2k** [comment]
> 
> 
> You wrap the handler you pass to the queue... - then it's all workers.

Oh, I see, so `NoParallelQueueHandler` is called exactly once; what is repeated is the returned function. Clever.

**Pull request closed without merging**
